version: "3.7"

x-env: &env
  # Logs
  LOG_SERIALIZE: "False"
  LOG_LEVEL: "DEBUG"
  # App
#  HOST: "localhost"
#  PORT: 8080
  APP_RELOAD: "True"
  APP_WORKERS: 1
  API_V1_STR: "v1"
  # Configuration
  CONFIGURATION_PATH: "./"

services:

  dhruv-email-integration:
    container_name: dhruv-email-integration
    build: ../app
    command: uvicorn app.main:app --reload --workers 2 --host 0.0.0.0 --port 80
    restart: always
    # volumes being used only for hot reload, comment for prod
#    volumes:
#      - ../../attachments:../../attachments
    ports:
      - "80:80"
    environment:
      <<: *env


  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "change_this_password"
      ACCEPT_EULA: "Y"

#  postgres:
#    image: postgres:10.5
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    logging:
#      options:
#        max-size: 10m
#        max-file: "3"
#    ports:
#      - '5438:5432'
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data