tenant: "SYSTEM"

# DB
db_url: "dialect+driver://user:<db_pwd>@host:port/<db_name>"
db_pwd: "abcdefg"
db_sales97_name: "db1"
db_fit_name: "db2"
db_mailstore_name: "db3"
# AWS
aws_access_key_id: "key"
aws_access_secret: "secret"
aws_region: "region"
aws_output: "json_or_something_else"
# AWS S3
s3_bucket: "app root folder link"
s3_default_bucket: "app default folder link"

